### ISSUE TITLE
add this library on npmjs

### ISSUE THREAD

**Issue by Nek-** [flyover/box2d.ts#37]
Also having a version tag would be nice

**Comment by chapterjason** [comment]
You can install it without having it on npmjs.

**Comment by Nek-** [comment]
Of course. And by the way, I recommend the following configuration `"@flyover/box2d": "github:flyover/box2d.ts#master"` which is also compatible with yarn.

But it would be better to have it on npm.

**Comment by WowMuchName** [comment]
While you can import the library the ways described above it is hardly a good idea.
If you really want to do it that way, depend on a commit - not master. That way you at least depend on a stable version that wont change in ways that might break your code.

Stumbling over this project I am really impressed with the work that was put into it. However, having it not be properly versioned means I am not going to use it for any serious project.

A 3 year old version of this project is already on npm as 0.0.1. There is no work to be done apart from calling npm publish when the project is updated. This seems like a reasonable time investment, in particular since the entry on npm suggests that the project is dead.

**Comment by Nek-** [comment]
Indeed, my config suggestion was an example. Anybody should prefer a commit version.

AFAIK there's nothing on npm named "@flyover/box2d". Maybe you speak about node-box2d ( https://www.npmjs.com/package/@flyover/node-box2d ). Notice that:
- it is not the same project
- here it is typescript (frontend compliant)

**Comment by WowMuchName** [comment]
Yes you are right about it not being the same project. It's just similar named.

**Comment by Fxlr8** [comment]
any updates on this one?

**Comment by Nek-** [comment]
@flyover would you authorize sombody to release on npmjs/yarnpkg ?

**Comment by flyover** [comment]
https://www.npmjs.com/package/@flyover/box2d

**Comment by Nek-** [comment]
Thanks @flyover
